# This is a workflow to perform basic verification for KoLmafia ASH scripts

name: CI
env:
  MAFIA_BUILD: "1938"
  MAFIA_VERSION: "20430"
  SCRIPT_NAMES: "autoscend.ash auto_pre_adv.ash auto_post_adv.ash auto_choice_adv.ash relay_autoscend.ash autoscend_quests.ash"

on: [push, pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8

    - name: Prepare KoLmafia
      run: |
        if [[ ! -f ".github/kolmafia.jar" ]]; then
          curl "https://ci.kolmafia.us/job/Kolmafia/${MAFIA_BUILD}/artifact/dist/KoLmafia-${MAFIA_VERSION}.jar" --output .github/kolmafia.jar
        fi
    
    - name: Install and verify
      run: |
        cd RELEASE

        if [[ -f "dependencies.txt" ]]; then
          # Install dependencies
          echo "Installing dependencies..."

          output_file="scripts/_ci_dependencies.ash"
          while read -r line || [ -n "$line" ]; do
            echo "cli_execute('svn checkout ${line}');" >> "$output_file"
          done < "dependencies.txt"
          echo "cli_execute('exit');" >> "$output_file"
          java -DuseCWDasROOT=true -jar ../.github/kolmafia.jar --CLI _ci_dependencies
        fi

        errors=0
        for ashfile in ${SCRIPT_NAMES}; do
            # Run the verification
            echo "Verifying ${ashfile}..."

            echo "try { cli_execute('verify ${ashfile}'); } finally { cli_execute('exit'); }" > scripts/_ci_verify.ash
            output=$(java -DuseCWDasROOT=true -jar ../.github/kolmafia.jar --CLI _ci_verify)
            if [[ $output == *"Script verification complete." ]]; then
                echo "Verified ${ashfile}!"
            else
                echo $output
                errors=$((errors+1))
            fi
        done

        exit ${errors}
